version: "3"
services:
  web:
    build: .
    ports:
      - "8085:5000"
    volumes:
      - vol1:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"

volumes: 
    vol1:
